const ExclusaoCliente = async (cli_id : number) => {
    try {
        console.log(cli_id, 'puta que pariu caralho')
        const resultado = await fetch ('http://localhost:32831/cliente/excluir', {
            method: 'DELETE',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ id: cli_id})
        })
        if (resultado.ok) {
            console.log('Exclus達o realizada com sucesso')
            return {success: true, message: 'Exclus達o realizada com sucesso'}
        }
        console.log('Erro ao realizar a exclus達o')
        return {success: false, message: 'Erro ao realizar a exclus達o'}
    }catch (error) {
            console.error('Erro ao excluir o cliente', error)
            throw new Error('Erro ao excluir o cliente')
        }

}

export default ExclusaoCliente